services:
  qdrant-db:
    container_name: qdrant-db
    image: qdrant/qdrant:latest
    ports:
      - '6333:6333'
  
  postgres-db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'