services:
  qdrant-db:
    container_name: qdrant-db
    image: qdrant/qdrant:latest
    ports:
      - '6333:6333'
    networks:
      - mevy-network
    restart: unless-stopped
  
  postgres-db:
    container_name: postgres-db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - mevy-network
    restart: unless-stopped
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - mevy-network
    restart: unless-stopped
  
networks:
  mevy-network:
    name: mevy-network
    driver: bridge