services:
  n8n:
    container_name: n8n
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=user
      - N8N_BASIC_AUTH_PASSWORD=password
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=n8n-db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n
      - NODE_FUNCTION_ALLOW_EXTERNAL=axios,qs
    depends_on:
      - n8n-db
    networks:
      - mevy-chatbot-network

  n8n-db:
    container_name: n8n-db
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n
      - POSTGRES_DB=n8n
    networks:
      - mevy-chatbot-network
  
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    ports:
      - '6333:6333'
      - '6334:6334'
    networks:
      - mevy-chatbot-network
    volumes:
      - qdrant-data:/qdrant/storage
    
  legifrance-service:
    container_name: legifrance_service
    build: ..
    ports:
      - '8000:8000'
    networks:
    - mevy-chatbot-network

volumes:
  db-data:
  qdrant-data:

networks:
  mevy-chatbot-network:
    driver: bridge
