name: CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: write-all

jobs:
  publish_image:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build Docker image
        run: |
          docker build -t ghcr.io/williammadie/mevy-bot:latest .
          docker run -d -p 80:80 ghcr.io/williammadie/mevy-bot:latest
          docker push ghcr.io/williammadie/mevy-bot:latest